const questions = [
  // ─── NBA ─── FACILE ────────────────────────────────────────────────────────
  {
    id: 1,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Quel joueur a remporté le plus de titres NBA en tant que joueur ?',
    options: ['Bill Russell', 'Michael Jordan', 'LeBron James', 'Kobe Bryant'],
    answer: 'Bill Russell',
    points: 100,
  },
  {
    id: 2,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Quelle équipe NBA est surnommée les "Bulls" ?',
    options: ['Chicago', 'Miami', 'Boston', 'Los Angeles'],
    answer: 'Chicago',
    points: 100,
  },
  {
    id: 3,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Combien de joueurs sont sur le terrain par équipe en NBA ?',
    options: ['5', '6', '4', '7'],
    answer: '5',
    points: 100,
  },
  {
    id: 4,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Qui est surnommé "King James" ?',
    options: ['LeBron James', 'James Harden', 'Kevin Durant', 'Giannis Antetokounmpo'],
    answer: 'LeBron James',
    points: 100,
  },
  {
    id: 5,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Quelle ville représente les Lakers ?',
    options: ['Los Angeles', 'New York', 'Chicago', 'Houston'],
    answer: 'Los Angeles',
    points: 100,
  },
  {
    id: 6,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Quel numéro portait Michael Jordan aux Chicago Bulls ?',
    options: ['23', '24', '33', '45'],
    answer: '23',
    points: 100,
  },
  {
    id: 7,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Combien de points vaut un tir à 3 points ?',
    options: ['3', '2', '4', '1'],
    answer: '3',
    points: 100,
  },
  {
    id: 8,
    category: 'NBA',
    difficulty: 'facile',
    question: 'Quelle équipe joue à Boston ?',
    options: ['Celtics', 'Nets', 'Bucks', 'Raptors'],
    answer: 'Celtics',
    points: 100,
  },

  // ─── NBA ─── MOYEN ────────────────────────────────────────────────────────
  {
    id: 9,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Qui détient le record du plus grand nombre de points marqués dans un seul match NBA ?',
    options: ['Wilt Chamberlain', 'Kobe Bryant', 'Michael Jordan', 'LeBron James'],
    answer: 'Wilt Chamberlain',
    points: 200,
  },
  {
    id: 10,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Combien de titres NBA Stephen Curry a-t-il remportés avec Golden State ?',
    options: ['4', '3', '2', '5'],
    answer: '4',
    points: 200,
  },
  {
    id: 11,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Quel joueur est connu sous le surnom "The Greek Freak" ?',
    options: ['Giannis Antetokounmpo', 'Nikola Jokic', 'Luka Doncic', 'Joel Embiid'],
    answer: 'Giannis Antetokounmpo',
    points: 200,
  },
  {
    id: 12,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'En quelle année les Miami Heat ont-ils remporté leur premier titre NBA ?',
    options: ['2006', '2004', '2010', '2012'],
    answer: '2006',
    points: 200,
  },
  {
    id: 13,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Quel joueur a remporté le plus de titres de MVP de la saison régulière NBA ?',
    options: ['Kareem Abdul-Jabbar', 'Michael Jordan', 'LeBron James', 'Bill Russell'],
    answer: 'Kareem Abdul-Jabbar',
    points: 200,
  },
  {
    id: 14,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Quel est le surnom des San Antonio Spurs ?',
    options: ['The Spurs', 'Big Three', 'Silver & Black', 'Los Cowboys'],
    answer: 'Silver & Black',
    points: 200,
  },
  {
    id: 15,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Nikola Jokic a remporté le MVP NBA en 2021 avec quelle équipe ?',
    options: ['Denver Nuggets', 'Utah Jazz', 'Oklahoma City Thunder', 'Portland Trail Blazers'],
    answer: 'Denver Nuggets',
    points: 200,
  },
  {
    id: 16,
    category: 'NBA',
    difficulty: 'moyen',
    question: 'Combien de fois Kobe Bryant a-t-il été champion NBA ?',
    options: ['5', '4', '6', '3'],
    answer: '5',
    points: 200,
  },

  // ─── NBA ─── DIFFICILE ────────────────────────────────────────────────────
  {
    id: 17,
    category: 'NBA',
    difficulty: 'difficile',
    question: 'Quel joueur a scoré 100 points dans un seul match NBA en 1962 ?',
    options: ['Wilt Chamberlain', 'Oscar Robertson', 'Jerry West', 'Bob Pettit'],
    answer: 'Wilt Chamberlain',
    points: 300,
  },
  {
    id: 18,
    category: 'NBA',
    difficulty: 'difficile',
    question: 'Quelle équipe a remporté le premier titre NBA en 1947 ?',
    options: ['Philadelphia Warriors', 'Boston Celtics', 'Minneapolis Lakers', 'New York Knicks'],
    answer: 'Philadelphia Warriors',
    points: 300,
  },
  {
    id: 19,
    category: 'NBA',
    difficulty: 'difficile',
    question: 'Quel joueur détient le record NBA de passes décisives en carrière ?',
    options: ['John Stockton', 'Magic Johnson', 'Steve Nash', 'Jason Kidd'],
    answer: 'John Stockton',
    points: 300,
  },
  {
    id: 20,
    category: 'NBA',
    difficulty: 'difficile',
    question: 'En quelle année la ligne à 3 points a-t-elle été introduite en NBA ?',
    options: ['1979', '1975', '1983', '1985'],
    answer: '1979',
    points: 300,
  },
  {
    id: 21,
    category: 'NBA',
    difficulty: 'difficile',
    question: 'Quel coach NBA détient le record de victoires en saison régulière ?',
    options: ['Don Nelson', 'Phil Jackson', 'Gregg Popovich', 'Pat Riley'],
    answer: 'Don Nelson',
    points: 300,
  },

  // ─── NCAA ─── FACILE ───────────────────────────────────────────────────────
  {
    id: 22,
    category: 'NCAA',
    difficulty: 'facile',
    question: 'Comment appelle-t-on le tournoi NCAA de basket masculin ?',
    options: ['March Madness', 'Final Four', 'Big Dance', 'College Cup'],
    answer: 'March Madness',
    points: 100,
  },
  {
    id: 23,
    category: 'NCAA',
    difficulty: 'facile',
    question: 'Combien d\'équipes participent au tournoi NCAA ?',
    options: ['68', '64', '32', '128'],
    answer: '68',
    points: 100,
  },
  {
    id: 24,
    category: 'NCAA',
    difficulty: 'facile',
    question: 'Quelle université représentent les Duke Blue Devils ?',
    options: ['Duke University', 'North Carolina', 'Kentucky', 'UCLA'],
    answer: 'Duke University',
    points: 100,
  },
  {
    id: 25,
    category: 'NCAA',
    difficulty: 'facile',
    question: 'LeBron James a-t-il joué au basket universitaire NCAA ?',
    options: ['Non', 'Oui, à Kentucky', 'Oui, à Ohio State', 'Oui, à Duke'],
    answer: 'Non',
    points: 100,
  },

  // ─── NCAA ─── MOYEN ───────────────────────────────────────────────────────
  {
    id: 26,
    category: 'NCAA',
    difficulty: 'moyen',
    question: 'Quelle université détient le plus de titres NCAA masculins ?',
    options: ['UCLA', 'Kentucky', 'Duke', 'North Carolina'],
    answer: 'UCLA',
    points: 200,
  },
  {
    id: 27,
    category: 'NCAA',
    difficulty: 'moyen',
    question: 'Comment s\'appelle le trophée remis au meilleur joueur du tournoi NCAA ?',
    options: ['Most Outstanding Player', 'MVP Award', 'Wooden Award', 'Final Four Trophy'],
    answer: 'Most Outstanding Player',
    points: 200,
  },
  {
    id: 28,
    category: 'NCAA',
    difficulty: 'moyen',
    question: 'Dans quelle université Michael Jordan a-t-il joué avant la NBA ?',
    options: ['North Carolina', 'Duke', 'Georgetown', 'Indiana'],
    answer: 'North Carolina',
    points: 200,
  },
  {
    id: 29,
    category: 'NCAA',
    difficulty: 'moyen',
    question: 'Quel entraîneur NCAA a le plus de victoires en tournoi March Madness ?',
    options: ['Mike Krzyzewski', 'Roy Williams', 'John Wooden', 'Bob Knight'],
    answer: 'Mike Krzyzewski',
    points: 200,
  },

  // ─── NCAA ─── DIFFICILE ───────────────────────────────────────────────────
  {
    id: 30,
    category: 'NCAA',
    difficulty: 'difficile',
    question: 'Quelle équipe a réussi un "perfect season" 32-0 pour gagner le titre NCAA en 1976 ?',
    options: ['Indiana Hoosiers', 'UCLA Bruins', 'North Carolina', 'Kentucky Wildcats'],
    answer: 'Indiana Hoosiers',
    points: 300,
  },
  {
    id: 31,
    category: 'NCAA',
    difficulty: 'difficile',
    question: 'Quel joueur a remporté le Wooden Award du meilleur joueur universitaire 3 fois ?',
    options: ['Oscar Robertson', 'Bill Walton', 'Pete Maravich', 'Larry Bird'],
    answer: 'Bill Walton',
    points: 300,
  },
  {
    id: 32,
    category: 'NCAA',
    difficulty: 'difficile',
    question: 'En quelle année le shot-clock de 35 secondes a-t-il été adopté en NCAA ?',
    options: ['1985', '1980', '1990', '1975'],
    answer: '1985',
    points: 300,
  },

  // ─── FRANCE ─── FACILE ────────────────────────────────────────────────────
  {
    id: 33,
    category: 'France',
    difficulty: 'facile',
    question: 'Comment s\'appelle le championnat de basket professionnel français ?',
    options: ['Betclic Élite', 'Pro A', 'Ligue Nationale', 'Division 1'],
    answer: 'Betclic Élite',
    points: 100,
  },
  {
    id: 34,
    category: 'France',
    difficulty: 'facile',
    question: 'Quel joueur français a été sélectionné en 1ère position de la Draft NBA 2023 ?',
    options: ['Victor Wembanyama', 'Bilal Coulibaly', 'Killian Hayes', 'Nicolas Batum'],
    answer: 'Victor Wembanyama',
    points: 100,
  },
  {
    id: 35,
    category: 'France',
    difficulty: 'facile',
    question: 'Quel club français de basket est basé à Paris ?',
    options: ['Paris Basketball', 'Roanne', 'Dijon', 'Monaco'],
    answer: 'Paris Basketball',
    points: 100,
  },
  {
    id: 36,
    category: 'France',
    difficulty: 'facile',
    question: 'Tony Parker a joué pour quelle équipe NBA pendant la majorité de sa carrière ?',
    options: ['San Antonio Spurs', 'Miami Heat', 'Los Angeles Lakers', 'Chicago Bulls'],
    answer: 'San Antonio Spurs',
    points: 100,
  },
  {
    id: 37,
    category: 'France',
    difficulty: 'facile',
    question: 'Combien de médailles d\'or l\'équipe de France a-t-elle remportées aux Jeux Olympiques ?',
    options: ['0', '1', '2', '3'],
    answer: '1',
    points: 100,
  },

  // ─── FRANCE ─── MOYEN ────────────────────────────────────────────────────
  {
    id: 38,
    category: 'France',
    difficulty: 'moyen',
    question: 'Tony Parker a-t-il remporté le titre de MVP des Finales NBA ?',
    options: ['Oui, en 2007', 'Non, jamais', 'Oui, en 2005', 'Oui, en 2003'],
    answer: 'Oui, en 2007',
    points: 200,
  },
  {
    id: 39,
    category: 'France',
    difficulty: 'moyen',
    question: 'Quel club français a remporté le plus de titres de champion de France ?',
    options: ['Limoges CSP', 'ASVEL', 'Paris Levallois', 'Cholet'],
    answer: 'Limoges CSP',
    points: 200,
  },
  {
    id: 40,
    category: 'France',
    difficulty: 'moyen',
    question: 'Dans quelle ville est basé l\'ASVEL, club phare du basket français ?',
    options: ['Villeurbanne', 'Lyon', 'Marseille', 'Bordeaux'],
    answer: 'Villeurbanne',
    points: 200,
  },
  {
    id: 41,
    category: 'France',
    difficulty: 'moyen',
    question: 'Quel joueur français a été le premier à être sélectionné en NBA Draft en 1er rang (avant Wembanyama) ?',
    options: ['Aucun', 'Tony Parker', 'Joakim Noah', 'Evan Fournier'],
    answer: 'Aucun',
    points: 200,
  },
  {
    id: 42,
    category: 'France',
    difficulty: 'moyen',
    question: 'La France a remporté la médaille d\'or olympique en basket à quel JO ?',
    options: ['Paris 2024', 'Tokyo 2020', 'Rio 2016', 'Londres 2012'],
    answer: 'Paris 2024',
    points: 200,
  },

  // ─── FRANCE ─── DIFFICILE ────────────────────────────────────────────────
  {
    id: 43,
    category: 'France',
    difficulty: 'difficile',
    question: 'En quelle année la Pro A (Betclic Élite) a-t-elle été créée sous ce format ?',
    options: ['1987', '1982', '1995', '2000'],
    answer: '1987',
    points: 300,
  },
  {
    id: 44,
    category: 'France',
    difficulty: 'difficile',
    question: 'Quel joueur français détient le record de points en un seul match de Betclic Élite ?',
    options: ['Antoine Rigaudeau', 'Tony Parker', 'Jim Bilba', 'Laurent Foirest'],
    answer: 'Antoine Rigaudeau',
    points: 300,
  },
  {
    id: 45,
    category: 'France',
    difficulty: 'difficile',
    question: 'Quel club français a remporté l\'EuroCoupe (anciennement ULEB Cup) ?',
    options: ['Paris Basketball', 'ASVEL', 'Limoges CSP', 'Cholet'],
    answer: 'ASVEL',
    points: 300,
  },

  // ─── EUROLEAGUE ─── FACILE ───────────────────────────────────────────────
  {
    id: 46,
    category: 'EuroLeague',
    difficulty: 'facile',
    question: 'Quelle équipe espagnole est la plus titrée en EuroLeague ?',
    options: ['Real Madrid', 'FC Barcelone', 'Unicaja', 'Valence'],
    answer: 'Real Madrid',
    points: 100,
  },
  {
    id: 47,
    category: 'EuroLeague',
    difficulty: 'facile',
    question: 'Dans quelle ville joue le CSKA Moscou, club phare de l\'EuroLeague ?',
    options: ['Moscou', 'Saint-Pétersbourg', 'Kazan', 'Kiev'],
    answer: 'Moscou',
    points: 100,
  },
  {
    id: 48,
    category: 'EuroLeague',
    difficulty: 'facile',
    question: 'Comment s\'appelle la finale de l\'EuroLeague ?',
    options: ['Final Four', 'Champions Game', 'Euro Final', 'Grand Final'],
    answer: 'Final Four',
    points: 100,
  },
  {
    id: 49,
    category: 'EuroLeague',
    difficulty: 'facile',
    question: 'Quel club grec est une référence de l\'EuroLeague ?',
    options: ['Panathinaïkos', 'Olympiakos', 'Les deux', 'Aucun'],
    answer: 'Les deux',
    points: 100,
  },

  // ─── EUROLEAGUE ─── MOYEN ───────────────────────────────────────────────
  {
    id: 50,
    category: 'EuroLeague',
    difficulty: 'moyen',
    question: 'Quel joueur détient le record de points en carrière en EuroLeague ?',
    options: ['Vassilis Spanoulis', 'Juan Carlos Navarro', 'Nando De Colo', 'Milos Teodosic'],
    answer: 'Vassilis Spanoulis',
    points: 200,
  },
  {
    id: 51,
    category: 'EuroLeague',
    difficulty: 'moyen',
    question: 'Quel club français participe régulièrement à l\'EuroLeague ?',
    options: ['ASVEL', 'Monaco', 'Paris Basketball', 'Dijon'],
    answer: 'ASVEL',
    points: 200,
  },
  {
    id: 52,
    category: 'EuroLeague',
    difficulty: 'moyen',
    question: 'En quelle année l\'EuroLeague a-t-elle été créée sous sa forme actuelle ?',
    options: ['2000', '1997', '2005', '1990'],
    answer: '2000',
    points: 200,
  },
  {
    id: 53,
    category: 'EuroLeague',
    difficulty: 'moyen',
    question: 'Combien d\'équipes participent à la phase régulière de l\'EuroLeague ?',
    options: ['18', '16', '20', '24'],
    answer: '18',
    points: 200,
  },
  {
    id: 54,
    category: 'EuroLeague',
    difficulty: 'moyen',
    question: 'Quel joueur français a été MVP du Final Four EuroLeague avec le CSKA ?',
    options: ['Nando De Colo', 'Tony Parker', 'Boris Diaw', 'Rodrigue Beaubois'],
    answer: 'Nando De Colo',
    points: 200,
  },

  // ─── EUROLEAGUE ─── DIFFICILE ───────────────────────────────────────────
  {
    id: 55,
    category: 'EuroLeague',
    difficulty: 'difficile',
    question: 'Quel club a remporté le premier titre EuroLeague en 2001 ?',
    options: ['Maccabi Tel Aviv', 'Real Madrid', 'Panathinaïkos', 'CSKA Moscou'],
    answer: 'Maccabi Tel Aviv',
    points: 300,
  },
  {
    id: 56,
    category: 'EuroLeague',
    difficulty: 'difficile',
    question: 'Quel entraîneur a remporté l\'EuroLeague avec 3 clubs différents ?',
    options: ['Ettore Messina', 'Pablo Laso', 'Zeljko Obradovic', 'Svetislav Pesic'],
    answer: 'Zeljko Obradovic',
    points: 300,
  },
  {
    id: 57,
    category: 'EuroLeague',
    difficulty: 'difficile',
    question: 'Combien de fois le CSKA Moscou a-t-il remporté l\'EuroLeague ?',
    options: ['8', '5', '10', '6'],
    answer: '8',
    points: 300,
  },
  {
    id: 58,
    category: 'EuroLeague',
    difficulty: 'difficile',
    question: 'Quel joueur turc est considéré comme une légende de l\'EuroLeague avec Fenerbahçe et Efes ?',
    options: ['Dogus Balbay', 'Mirsad Türkcan', 'Hidayet Türkoğlu', 'Semih Erden'],
    answer: 'Hidayet Türkoğlu',
    points: 300,
  },
];

module.exports = { questions };
